modLoader="javafml"
loaderVersion="[4,)"
license="Academic Free License v3.0"

[[mods]]
modId="bugs_aplenty"
version="1.0.0"
displayName="Bugs Aplenty"
displayURL="http://prcrichards.wixsite.com/portfolio"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Mindthemoods"
description="Filled with bugs!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.bugs_aplenty]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.bugs_aplenty]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"


[[dependencies.bugs_aplenty]]
modId="geckolib"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"


[[mixins]]
    config="mixins.bugs_aplenty.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration